version: "3"

services:
  bot:
    container_name: discord_bot
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - ./bot/src:/app
    environment:
      - TOKEN=${TOKEN}
      - ENTRY_EXIT_MONITOR_VOICE_CHANNEL_ID=${ENTRY_EXIT_MONITOR_VOICE_CHANNEL_ID}
      - ENTRY_EXIT_MONITOR_NOTIFICATION_CHANNEL_ID=${ENTRY_EXIT_MONITOR_NOTIFICATION_CHANNEL_ID}
      - WEATHER_NOTIFICATION_CHANNEL_ID=${WEATHER_NOTIFICATION_CHANNEL_ID}
    command: ["python3", "main.py"]
