version: "3"

services:
  bot:
    container_name: discord_bot
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - ./bot/src:/app
    environment:
      - TOKEN=${TOKEN}
      - VOICE_CHANNEL_ID=${VOICE_CHANNEL_ID}
      - TEXT_CHANNEL_ID=${TEXT_CHANNEL_ID}
    command: ["python3", "main.py"]