version: "3"

services:
  bot:
    container_name: discord_bot
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - ./bot/src:/app
    environment:
      - TOKEN=${TOKEN}
    command: ["python3", "main.py"]
